# Generated by Django 4.2.3 on 2023-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed Run', max_length=100)),
                ('zone', models.PositiveSmallIntegerField(choices=[(1, 'Z1 - Recovery'), (2, 'Z2 - Base'), (3, 'Z3 - Tempo'), (4, 'Z4 - High Tempo'), (5, 'Z5 - Interval/Anaerobic')])),
                ('feel', models.CharField(choices=[('recovery', 'Recovery'), ('base', 'Base'), ('hard', 'Hard'), ('max-effort', 'Max Effort')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance', models.PositiveIntegerField(help_text='Distance in km')),
            ],
        ),
    ]
