# Generated by Django 4.2.3 on 2023-09-23 14:15

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import training_plan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in kilograms', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in centimeters', null=True)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('date_of_marathon', models.DateField(blank=True, help_text='Date of marathon', null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', training_plan.models.RunnerUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MarathonPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed Run', max_length=100)),
                ('zone', models.PositiveSmallIntegerField(choices=[(1, 'Z1 - Recovery'), (2, 'Z2 - Base'), (3, 'Z3 - Tempo'), (4, 'Z4 - High Tempo'), (5, 'Z5 - Interval/Anaerobic')])),
                ('feel', models.CharField(choices=[('recovery', 'Recovery'), ('base', 'Base'), ('hard', 'Hard'), ('max-effort', 'Max Effort')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance', models.PositiveIntegerField(help_text='Distance in km')),
                ('on', models.PositiveIntegerField(default=0, help_text='Work time in minutes')),
                ('off', models.PositiveIntegerField(default=0, help_text='Rest time in minutes')),
                ('sets', models.PositiveIntegerField(default=0, help_text='Sets')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledRuns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(default='Unnamed Run', max_length=100)),
                ('date', models.DateField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance', models.PositiveIntegerField(help_text='Distance in km')),
                ('marathon_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_plan.marathonplan')),
                ('run_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_plan.run')),
            ],
        ),
        migrations.AddField(
            model_name='runneruser',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_plan.marathonplan'),
        ),
        migrations.AddField(
            model_name='runneruser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='runneruser_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='runneruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='runneruser_set', to='auth.permission'),
        ),
    ]
