# Generated by Django 4.2.3 on 2023-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledruns',
            name='off',
            field=models.PositiveIntegerField(default=0, help_text='Rest time in minutes'),
        ),
        migrations.AddField(
            model_name='scheduledruns',
            name='on',
            field=models.PositiveIntegerField(default=0, help_text='Work time in minutes'),
        ),
        migrations.AddField(
            model_name='scheduledruns',
            name='sets',
            field=models.PositiveIntegerField(default=0, help_text='Sets'),
        ),
    ]
