# Generated by Django 4.2.3 on 2023-10-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runneruser',
            name='height',
        ),
        migrations.RemoveField(
            model_name='runneruser',
            name='weight',
        ),
    ]
