# Generated by Django 4.2.6 on 2023-10-22 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runneruser',
            name='date_of_marathon',
            field=models.DateField(default=datetime.date(2024, 4, 19), help_text='Date of marathon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runneruser',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'This field is required.'}, max_length=30),
        ),
        migrations.AlterField(
            model_name='runneruser',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'This field is required.'}, max_length=30),
        ),
    ]
