# Generated by Django 4.2.6 on 2023-11-01 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0002_alter_runneruser_date_of_marathon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runneruser',
            name='date_of_marathon',
            field=models.DateField(help_text='Date of marathon: 90-365 days from today, recommend 180+ days.'),
        ),
        migrations.AlterField(
            model_name='runneruser',
            name='dob',
            field=models.DateField(help_text='You must be at least 18 years old.', verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='runneruser',
            name='fitness_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='If you are unsure of your fitnes level, choose beginner.', max_length=50),
        ),
        migrations.CreateModel(
            name='StravaUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_access_token', models.CharField(max_length=200)),
                ('strava_refresh_token', models.CharField(max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
