# Generated by Django 4.2.3 on 2023-09-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0002_scheduledruns_off_scheduledruns_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('feedback', models.CharField(blank=True, choices=[('too_easy', 'Too Easy'), ('just_right', 'Just Right'), ('too_hard', 'Too Hard')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('marathon_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_plan.marathonplan')),
            ],
        ),
    ]
