# Generated by Django 4.2.6 on 2023-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0003_alter_runneruser_date_of_marathon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravauserprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
