# Generated by Django 4.2.3 on 2023-10-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0004_marathonplan_weeks_trainingweek_week_commencing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledRuns',
            new_name='ScheduledRun',
        ),
    ]
