# Generated by Django 4.2.6 on 2023-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0005_stravauserprofile_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedrun',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='stravauserprofile',
            name='client_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
