# Generated by Django 4.2.3 on 2023-10-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0006_remove_marathonplan_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='feel',
            field=models.CharField(choices=[('recovery', 'Recovery'), ('base', 'Base'), ('hard', 'Hard'), ('max-effort', 'Max Effort'), ('rest', 'Rest')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='zone',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Z1 - Recovery'), (2, 'Z2 - Base'), (3, 'Z3 - Tempo'), (4, 'Z4 - High Tempo'), (5, 'Z5 - Interval/Anaerobic'), (0, 'Rest')]),
        ),
    ]
